-- Schemas and roles are created by portfolio-infra/supabase/bootstrap.sql in production
-- (db/local-roles.sql locally); "if not exists" keeps this migration runnable in both.
create schema if not exists dash;
create schema if not exists dash_demo;

-- App data -------------------------------------------------------------------

create table dash.dashboards (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null,
  title text not null,
  spec jsonb not null,
  contract_version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index on dash.dashboards (owner_id);

create table dash.memberships (
  user_id uuid not null,
  tenant_id int not null,
  primary key (user_id, tenant_id)
);

alter table dash.dashboards enable row level security;
alter table dash.memberships enable row level security;

-- The server sets app.user_id per transaction; no policy exists for the Data API roles,
-- so anon and authenticated see nothing.
create policy dashboards_owner on dash.dashboards to dash_app
  using (owner_id = nullif(current_setting('app.user_id', true), '')::uuid)
  with check (owner_id = nullif(current_setting('app.user_id', true), '')::uuid);
-- Memberships are assigned and looked up by the server itself (first sign-in, resolveScope).
create policy memberships_server on dash.memberships to dash_app using (true) with check (true);

grant usage on schema dash to dash_app;
grant select, insert, update, delete on dash.dashboards, dash.memberships to dash_app;

-- Demo source data -----------------------------------------------------------

create table dash_demo.tenants (
  id int primary key,
  name text not null,
  region text not null
);

create table dash_demo.customers (
  id int primary key,
  tenant_id int not null references dash_demo.tenants (id),
  name text not null,
  country text not null,
  segment text not null,
  created_at timestamptz not null default now()
);

create table dash_demo.products (
  id int primary key,
  tenant_id int not null references dash_demo.tenants (id),
  name text not null,
  category text not null,
  unit_price numeric(10, 2) not null
);

create table dash_demo.orders (
  id bigint generated by default as identity primary key,
  tenant_id int not null references dash_demo.tenants (id),
  customer_id int not null references dash_demo.customers (id),
  ordered_at timestamptz not null,
  status text not null,
  channel text not null
);
create index on dash_demo.orders (tenant_id, ordered_at);

create table dash_demo.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references dash_demo.orders (id) on delete cascade,
  tenant_id int not null references dash_demo.tenants (id),
  product_id int not null references dash_demo.products (id),
  quantity int not null,
  unit_price numeric(10, 2) not null
);
create index on dash_demo.order_items (order_id);

grant usage on schema dash_demo to dash_reader;
grant select on all tables in schema dash_demo to dash_reader;

-- Defense in depth (DESIGN.md §6): the gateway sets app.tenant_ids per transaction.
do $$
declare
  t text;
begin
  foreach t in array array['customers', 'products', 'orders', 'order_items'] loop
    execute format('alter table dash_demo.%I enable row level security', t);
    execute format(
      'create policy tenant_scope on dash_demo.%I for select to dash_reader using (tenant_id = any(string_to_array(current_setting(''app.tenant_ids'', true), '','')::int[]))',
      t
    );
  end loop;
end
$$;
alter table dash_demo.tenants enable row level security;
create policy tenant_scope on dash_demo.tenants for select to dash_reader
  using (id = any(string_to_array(current_setting('app.tenant_ids', true), ',')::int[]));
